# Generated by Django 4.1.5 on 2023-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='author',
        ),
        migrations.AddField(
            model_name='links',
            name='author_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ID пользователя'),
        ),
    ]
