# Generated by Django 4.1.5 on 2023-02-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_links_author_links_author_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
