# Generated by Django 4.1.5 on 2023-02-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_links_created_time_alter_links_full_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='created_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
