# Generated by Django 4.1.5 on 2023-02-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_links_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='created_time',
            field=models.DateTimeField(default='2023-02-10', verbose_name='Время создания'),
        ),
    ]
