# Generated by Django 4.1.5 on 2023-02-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_links_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
