# Generated by Django 4.1.5 on 2023-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.URLField(max_length=500, verbose_name='Полная ссылка')),
                ('short_link', models.CharField(max_length=50, verbose_name='Сокращенная ссылка')),
                ('author_id', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
